import type { EGXSymbol } from "@/types";

// COMPLETE AUDITED EGX SYMBOL LIST (254 Stocks)
export const EGX_SYMBOLS: EGXSymbol[] = [
  { symbol: "AALR", name: "General Co. for Land Reclamation Development & Reconstruction", shortName: "AALR", tvSymbol: "EGX:AALR" },
  { symbol: "ABUK", name: "Abou Kir Fertilizers & Chemical Industries Co.", shortName: "ABUK", tvSymbol: "EGX:ABUK" },
  { symbol: "ACAMD", name: "Arab Co. for Asset Management & Development", shortName: "ACAMD", tvSymbol: "EGX:ACAMD" },
  { symbol: "ACAP", name: "A Capital Holding", shortName: "ACAP", tvSymbol: "EGX:ACAP" },
  { symbol: "ACFR", name: "Alexandria Company For Refractories", shortName: "ACFR", tvSymbol: "EGX:ACFR" },
  { symbol: "ACGC", name: "Arab Cotton Ginning Co.", shortName: "ACGC", tvSymbol: "EGX:ACGC" },
  { symbol: "ACTF", name: "Act Financial", shortName: "ACTF", tvSymbol: "EGX:ACTF" },
  { symbol: "ADCI", name: "Arab Pharmaceuticals", shortName: "ADCI", tvSymbol: "EGX:ADCI" },
  { symbol: "ADIB", name: "Abu Dhabi Islamic Bank-Egypt", shortName: "ADIB", tvSymbol: "EGX:ADIB" },
  { symbol: "ADPC", name: "Arab Dairy Products Co. Arab Dairy - Panda", shortName: "ADPC", tvSymbol: "EGX:ADPC" },
  { symbol: "ADRI", name: "Arab Development & Real Estate Investment", shortName: "ADRI", tvSymbol: "EGX:ADRI" },
  { symbol: "AFDI", name: "Alahly For Development & Investment", shortName: "AFDI", tvSymbol: "EGX:AFDI" },
  { symbol: "AFMC", name: "Alexandria Flour Mills Co.", shortName: "AFMC", tvSymbol: "EGX:AFMC" },
  { symbol: "AIDC", name: "Arabia for Investment and Development", shortName: "AIDC", tvSymbol: "EGX:AIDC" },
  { symbol: "AIFI", name: "Atlas for Investment & Food Industries SAE", shortName: "AIFI", tvSymbol: "EGX:AIFI" },
  { symbol: "AIH", name: "Arabia Investments Holding SAE", shortName: "AIH", tvSymbol: "EGX:AIH" },
  { symbol: "AJWA", name: "Ajwa for Food Industries Co. Egypt", shortName: "AJWA", tvSymbol: "EGX:AJWA" },
  { symbol: "ALCN", name: "Alexandria Containers & Goods", shortName: "ALCN", tvSymbol: "EGX:ALCN" },
  { symbol: "ALUM", name: "Arab Aluminum Co. SAE", shortName: "ALUM", tvSymbol: "EGX:ALUM" },
  { symbol: "AMER", name: "Amer Group Holding", shortName: "AMER", tvSymbol: "EGX:AMER" },
  { symbol: "AMES", name: "Alexandria New Medical Center Co.", shortName: "AMES", tvSymbol: "EGX:AMES" },
  { symbol: "AMIA", name: "Arab Moltaqa Investments Company", shortName: "AMIA", tvSymbol: "EGX:AMIA" },
  { symbol: "AMOC", name: "Alexandria Mineral Oils Co.", shortName: "AMOC", tvSymbol: "EGX:AMOC" },
  { symbol: "AMPI", name: "AL Moasher Pay for Electronic Payment and Collection (S.A.E)", shortName: "AMPI", tvSymbol: "EGX:AMPI" },
  { symbol: "ANCC", name: "ALNAHDA Industrial Co.", shortName: "ANCC", tvSymbol: "EGX:ANCC" },
  { symbol: "ANFI", name: "Alexandria National Co. for Financial Investment", shortName: "ANFI", tvSymbol: "EGX:ANFI" },
  { symbol: "APSW", name: "Arab Polvara Spinning & Weaving Co.", shortName: "APSW", tvSymbol: "EGX:APSW" },
  { symbol: "ARAB", name: "Arab Developers Holding", shortName: "ARAB", tvSymbol: "EGX:ARAB" },
  { symbol: "ARCC", name: "Arabian Cement Company", shortName: "ARCC", tvSymbol: "EGX:ARCC" },
  { symbol: "AREH", name: "Egyptian Real Estate Group", shortName: "AREH", tvSymbol: "EGX:AREH" },
  { symbol: "ARVA", name: "Arab Valves Co.", shortName: "ARVA", tvSymbol: "EGX:ARVA" },
  { symbol: "ASCM", name: "ASEC Co. for Mining", shortName: "ASCM", tvSymbol: "EGX:ASCM" },
  { symbol: "ASPI", name: "Aspire Capital Holding for Financial Investments", shortName: "ASPI", tvSymbol: "EGX:ASPI" },
  { symbol: "ATLC", name: "Al Tawfeek Leasing Company-A.T.LEASE", shortName: "ATLC", tvSymbol: "EGX:ATLC" },
  { symbol: "ATQA", name: "Misr National Steel", shortName: "ATQA", tvSymbol: "EGX:ATQA" },
  { symbol: "AXPH", name: "Alexandria Company for Pharmaceuticals and Chemical Industries", shortName: "AXPH", tvSymbol: "EGX:AXPH" },
  { symbol: "BIDI", name: "El Badr Investment and Development - BID", shortName: "BIDI", tvSymbol: "EGX:BIDI" },
  { symbol: "BIGP", name: "ElBarbary Investment Group", shortName: "BIGP", tvSymbol: "EGX:BIGP" },
  { symbol: "BINV", name: "B Investments Holding SAE", shortName: "BINV", tvSymbol: "EGX:BINV" },
  { symbol: "BIOC", name: "GlaxoSmithKline S.A.E.", shortName: "BIOC", tvSymbol: "EGX:BIOC" },
  { symbol: "BONY", name: "Bonyan for Development and Trade", shortName: "BONY", tvSymbol: "EGX:BONY" },
  { symbol: "BTFH", name: "Beltone Holding", shortName: "BTFH", tvSymbol: "EGX:BTFH" },
  { symbol: "CAED", name: "Cairo Educational Services", shortName: "CAED", tvSymbol: "EGX:CAED" },
  { symbol: "CANA", name: "Suez Canal Bank SAE", shortName: "CANA", tvSymbol: "EGX:CANA" },
  { symbol: "CCAP", name: "QALA For Financial Investments", shortName: "CCAP", tvSymbol: "EGX:CCAP" },
  { symbol: "CCRS", name: "Gulf Canadian Real Estate Investment Co.", shortName: "CCRS", tvSymbol: "EGX:CCRS" },
  { symbol: "CEFM", name: "Middle Egypt Flour Mills", shortName: "CEFM", tvSymbol: "EGX:CEFM" },
  { symbol: "CERA", name: "Arab Ceramic Co. - Ceramica Remas", shortName: "CERA", tvSymbol: "EGX:CERA" },
  { symbol: "CFGH", name: "Concrete Fashion Group for Commercial and Industrial Investments S.A.E", shortName: "CFGH", tvSymbol: "EGX:CFGH" },
  { symbol: "CICH", name: "CI Capital Holding for Financial Investments", shortName: "CICH", tvSymbol: "EGX:CICH" },
  { symbol: "CIEB", name: "Credit Agricole Egypt", shortName: "CIEB", tvSymbol: "EGX:CIEB" },
  { symbol: "CIRA", name: "Cairo For Investment And Real Estate Developments -CIRA Education", shortName: "CIRA", tvSymbol: "EGX:CIRA" },
  { symbol: "CLHO", name: "Cleopatra Hospital Company", shortName: "CLHO", tvSymbol: "EGX:CLHO" },
  { symbol: "CNFN", name: "Contact Financial Holding SAE", shortName: "CNFN", tvSymbol: "EGX:CNFN" },
  { symbol: "COMI", name: "Commercial International Bank - Egypt (CIB) S.A.E.", shortName: "COMI", tvSymbol: "EGX:COMI" },
  { symbol: "COPR", name: "Cooper for Commercial Investment & Real Estate Development", shortName: "COPR", tvSymbol: "EGX:COPR" },
  { symbol: "COSG", name: "Cairo Oils & Soap", shortName: "COSG", tvSymbol: "EGX:COSG" },
  { symbol: "CPCI", name: "Kahira Pharmaceuticals & Chemical Industries Co.", shortName: "CPCI", tvSymbol: "EGX:CPCI" },
  { symbol: "CPME", name: "Catalyst Partners Middle East", shortName: "CPME", tvSymbol: "EGX:CPME" },
  { symbol: "CRST", name: "Creast Mark For Contracting And Real Estate Development", shortName: "CRST", tvSymbol: "EGX:CRST" },
  { symbol: "CSAG", name: "Canal Shipping Agencies Co.", shortName: "CSAG", tvSymbol: "EGX:CSAG" },
  { symbol: "DAPH", name: "Development & Engineering Consultants", shortName: "DAPH", tvSymbol: "EGX:DAPH" },
  { symbol: "DCCC", name: "Damietta Container and Cargo Handling", shortName: "DCCC", tvSymbol: "EGX:DCCC" },
  { symbol: "DEIN", name: "Delta Insurance", shortName: "DEIN", tvSymbol: "EGX:DEIN" },
  { symbol: "DGTZ", name: "Digitize for Investment And Technology", shortName: "DGTZ", tvSymbol: "EGX:DGTZ" },
  { symbol: "DOMT", name: "Arabian Food Industries Co.", shortName: "DOMT", tvSymbol: "EGX:DOMT" },
  { symbol: "DSCW", name: "Dice Sports & Casual Wear Manufacturers SAE", shortName: "DSCW", tvSymbol: "EGX:DSCW" },
  { symbol: "DTPP", name: "Delta for Printing & Packaging", shortName: "DTPP", tvSymbol: "EGX:DTPP" },
  { symbol: "EALR", name: "El Arabia for Land Reclamation", shortName: "EALR", tvSymbol: "EGX:EALR" },
  { symbol: "EASB", name: "Egyptian Arabian Company for Securities Brokerage EAC", shortName: "EASB", tvSymbol: "EGX:EASB" },
  { symbol: "EAST", name: "Eastern Company", shortName: "EAST", tvSymbol: "EGX:EAST" },
  { symbol: "EBSC", name: "Osool ESB Securities Brokerage", shortName: "EBSC", tvSymbol: "EGX:EBSC" },
  { symbol: "ECAP", name: "El Ezz Ceramics & Porcelain Co. (Gemma)", shortName: "ECAP", tvSymbol: "EGX:ECAP" },
  { symbol: "EDFM", name: "East Delta Flour Mills Co.", shortName: "EDFM", tvSymbol: "EGX:EDFM" },
  { symbol: "EEII", name: "El Arabia Engineering Industries", shortName: "EEII", tvSymbol: "EGX:EEII" },
  { symbol: "EFAC", name: "Egyptian Ferro All Egp10", shortName: "EFAC", tvSymbol: "EGX:EFAC" },
  { symbol: "EFIC", name: "Egyptian Financial & Industrial Co.", shortName: "EFIC", tvSymbol: "EGX:EFIC" },
  { symbol: "EFID", name: "Edita Food Industries SAE", shortName: "EFID", tvSymbol: "EGX:EFID" },
  { symbol: "EFIH", name: "e-finance for Digital and Financial Investments S.A.E.", shortName: "EFIH", tvSymbol: "EGX:EFIH" },
  { symbol: "EGAL", name: "Egypt Aluminum", shortName: "EGAL", tvSymbol: "EGX:EGAL" },
  { symbol: "EGAS", name: "Egypt Gas Co.", shortName: "EGAS", tvSymbol: "EGX:EGAS" },
  { symbol: "EGBE", name: "Egyptian Gulf Bank", shortName: "EGBE", tvSymbol: "EGX:EGBE" },
  { symbol: "EGCH", name: "Egyptian Chemical Industries", shortName: "EGCH", tvSymbol: "EGX:EGCH" },
  { symbol: "EGREF", name: "Egyptians Real Estate Fund", shortName: "EGREF", tvSymbol: "EGX:EGREF" },
  { symbol: "EGSA", name: "Egyptian Satellite Co.", shortName: "EGSA", tvSymbol: "EGX:EGSA" },
  { symbol: "EGTS", name: "Egyptian for Tourism Resorts", shortName: "EGTS", tvSymbol: "EGX:EGTS" },
  { symbol: "EGWA", name: "General Warehouses of Egypt", shortName: "EGWA", tvSymbol: "EGX:EGWA" },
  { symbol: "EHDR", name: "Egyptians Housing Development & Reconstruction", shortName: "EHDR", tvSymbol: "EGX:EHDR" },
  { symbol: "ELEC", name: "Electro Cable Egypt", shortName: "ELEC", tvSymbol: "EGX:ELEC" },
  { symbol: "ELKA", name: "El Kahera Housing", shortName: "ELKA", tvSymbol: "EGX:ELKA" },
  { symbol: "ELNA", name: "El Nasr for Manufacturing Agricultural Crops", shortName: "ELNA", tvSymbol: "EGX:ELNA" },
  { symbol: "ELSH", name: "El-Shams Housing & Development SA", shortName: "ELSH", tvSymbol: "EGX:ELSH" },
  { symbol: "ELWA", name: "Elwadi for International Investment & Development", shortName: "ELWA", tvSymbol: "EGX:ELWA" },
  { symbol: "EMFD", name: "Emaar Misr for Development SAE", shortName: "EMFD", tvSymbol: "EGX:EMFD" },
  { symbol: "ENGC", name: "Industrial Engineering Co. for Construction & Development", shortName: "ENGC", tvSymbol: "EGX:ENGC" },
  { symbol: "EOSB", name: "El Orouba Securities Brokerage", shortName: "EOSB", tvSymbol: "EGX:EOSB" },
  { symbol: "EPCO", name: "Egypt for Poultry Co.", shortName: "EPCO", tvSymbol: "EGX:EPCO" },
  { symbol: "EPPK", name: "El Ahram Co. for Printing & Packing", shortName: "EPPK", tvSymbol: "EGX:EPPK" },
  { symbol: "ETEL", name: "Telecom Egypt", shortName: "ETEL", tvSymbol: "EGX:ETEL" },
  { symbol: "ETRS", name: "Egyptian Transport & Commercial Services Co. SAE", shortName: "ETRS", tvSymbol: "EGX:ETRS" },
  { symbol: "EXPA", name: "Export Development Bank of Egypt", shortName: "EXPA", tvSymbol: "EGX:EXPA" },
  { symbol: "FAIT", name: "Faisal Islamic Bank of Egypt", shortName: "FAIT", tvSymbol: "EGX:FAIT" },
  { symbol: "FAITA", name: "Faisal Islamic Bank of Egypt", shortName: "FAITA", tvSymbol: "EGX:FAITA" },
  { symbol: "FCMD", name: "International Company for Medical Industries", shortName: "FCMD", tvSymbol: "EGX:FCMD" },
  { symbol: "FIRE", name: "First Investment & Real Estate Development", shortName: "FIRE", tvSymbol: "EGX:FIRE" },
  { symbol: "FNAR", name: "Al Fanar Contracting Construction Trade Import & Export Co.", shortName: "FNAR", tvSymbol: "EGX:FNAR" },
  { symbol: "FTNS", name: "Fitness Prime", shortName: "FTNS", tvSymbol: "EGX:FTNS" },
  { symbol: "FWRY", name: "Fawry For Banking Technology And Electronic Payment", shortName: "FWRY", tvSymbol: "EGX:FWRY" },
  { symbol: "GBCO", name: "GB Corp", shortName: "GBCO", tvSymbol: "EGX:GBCO" },
  { symbol: "GDWA", name: "Gadwa For Industrial Development", shortName: "GDWA", tvSymbol: "EGX:GDWA" },
  { symbol: "GEOS", name: "Geos for trading and contracting", shortName: "GEOS", tvSymbol: "EGX:GEOS" },
  { symbol: "GGCC", name: "Giza General Contracting & Real Estate Investment", shortName: "GGCC", tvSymbol: "EGX:GGCC" },
  { symbol: "GGRN", name: "Gogreen for Agricultural Investment and Development Company", shortName: "GGRN", tvSymbol: "EGX:GGRN" },
  { symbol: "GIHD", name: "Gharbia Islamic Housing Development", shortName: "GIHD", tvSymbol: "EGX:GIHD" },
  { symbol: "GMCI", name: "GMC Group for Industrial Commercial & Financial Investments", shortName: "GMCI", tvSymbol: "EGX:GMCI" },
  { symbol: "GOUR", name: "Gourmet Egypt.Com Foods", shortName: "GOUR", tvSymbol: "EGX:GOUR" },
  { symbol: "GPIM", name: "GPI For Urban Growth", shortName: "GPIM", tvSymbol: "EGX:GPIM" },
  { symbol: "GPPL", name: "Golden Pyramids Plaza", shortName: "GPPL", tvSymbol: "EGX:GPPL" },
  { symbol: "GRCA", name: "Grand Investment Capital", shortName: "GRCA", tvSymbol: "EGX:GRCA" },
  { symbol: "GSSC", name: "General Silos & Storage Co.", shortName: "GSSC", tvSymbol: "EGX:GSSC" },
  { symbol: "GTEX", name: "G-TEX for Commercial and Industrial Investments S.A.E", shortName: "GTEX", tvSymbol: "EGX:GTEX" },
  { symbol: "GTWL", name: "Golden Textiles & Clothes Wool", shortName: "GTWL", tvSymbol: "EGX:GTWL" },
  { symbol: "HAVC", name: "Hassan Allam Investments & Venture Capital S.A.E", shortName: "HAVC", tvSymbol: "EGX:HAVC" },
  { symbol: "HBCO", name: "Heibco Npv", shortName: "HBCO", tvSymbol: "EGX:HBCO" },
  { symbol: "HDBK", name: "Housing & Development Bank", shortName: "HDBK", tvSymbol: "EGX:HDBK" },
  { symbol: "HDST", name: "HEDGESTONE INVESTMENT", shortName: "HDST", tvSymbol: "EGX:HDST" },
  { symbol: "HELI", name: "Heliopolis Housing", shortName: "HELI", tvSymbol: "EGX:HELI" },
  { symbol: "HRHO", name: "EFG Holding S.A.E.", shortName: "HRHO", tvSymbol: "EGX:HRHO" },
  { symbol: "IBCT", name: "International Business Corp. for Trading & Agencies", shortName: "IBCT", tvSymbol: "EGX:IBCT" },
  { symbol: "ICFC", name: "International Co. for Fertilizers & Chemicals", shortName: "ICFC", tvSymbol: "EGX:ICFC" },
  { symbol: "ICID", name: "International Company for Investment & Development", shortName: "ICID", tvSymbol: "EGX:ICID" },
  { symbol: "ICLE", name: "International Co. for Leasing SAE", shortName: "ICLE", tvSymbol: "EGX:ICLE" },
  { symbol: "IDRE", name: "Ismailia Development & Real Estate Co.", shortName: "IDRE", tvSymbol: "EGX:IDRE" },
  { symbol: "IEEC", name: "Industrial & Engineering Enterprises Co.", shortName: "IEEC", tvSymbol: "EGX:IEEC" },
  { symbol: "IFAP", name: "International Agricultural Products", shortName: "IFAP", tvSymbol: "EGX:IFAP" },
  { symbol: "INEG", name: "Integrated Engineering Group S.A.E", shortName: "INEG", tvSymbol: "EGX:INEG" },
  { symbol: "INFI", name: "Ismailia National Food Industries", shortName: "INFI", tvSymbol: "EGX:INFI" },
  { symbol: "IRON", name: "Egyptian Iron & Steel", shortName: "IRON", tvSymbol: "EGX:IRON" },
  { symbol: "ISMA", name: "Ismailia Misr Poultry", shortName: "ISMA", tvSymbol: "EGX:ISMA" },
  { symbol: "ISMQ", name: "Iron & Steel for Mines & Quarries", shortName: "ISMQ", tvSymbol: "EGX:ISMQ" },
  { symbol: "ISPH", name: "Ibnsina Pharma", shortName: "ISPH", tvSymbol: "EGX:ISPH" },
  { symbol: "JUFO", name: "Juhayna Food Industries", shortName: "JUFO", tvSymbol: "EGX:JUFO" },
  { symbol: "KABO", name: "El Nasr Clothing & Textiles Co.", shortName: "KABO", tvSymbol: "EGX:KABO" },
  { symbol: "KNGC", name: "EL- Nasr Glass And Crystal", shortName: "KNGC", tvSymbol: "EGX:KNGC" },
  { symbol: "KORA", name: "KORRA", shortName: "KORA", tvSymbol: "EGX:KORA" },
  { symbol: "KRDI", name: "Al Khair River for Development Agriculture Investment and Environmental Services", shortName: "KRDI", tvSymbol: "EGX:KRDI" },
  { symbol: "KWIN", name: "El Kahera El Watania Investment", shortName: "KWIN", tvSymbol: "EGX:KWIN" },
  { symbol: "KZPC", name: "Kafr El Zayat Pesticides & Chemical Co.", shortName: "KZPC", tvSymbol: "EGX:KZPC" },
  { symbol: "LCSW", name: "Lecico Egypt SAE", shortName: "LCSW", tvSymbol: "EGX:LCSW" },
  { symbol: "LUTS", name: "Lotus For Agricultural Investments And Development", shortName: "LUTS", tvSymbol: "EGX:LUTS" },
  { symbol: "MAAL", name: "Marseilla Al Masreia Al Khalegeya for Holding Investment", shortName: "MAAL", tvSymbol: "EGX:MAAL" },
  { symbol: "MASR", name: "Madinet Masr for Housing & Development", shortName: "MASR", tvSymbol: "EGX:MASR" },
  { symbol: "MBEG", name: "MB for Engineering & Contracting", shortName: "MBEG", tvSymbol: "EGX:MBEG" },
  { symbol: "MBSC", name: "Misr Beni Suef Cement Co. SAE", shortName: "MBSC", tvSymbol: "EGX:MBSC" },
  { symbol: "MCQE", name: "Misr Cement Co. (Qena)", shortName: "MCQE", tvSymbol: "EGX:MCQE" },
  { symbol: "MCRO", name: "Macro Group Pharmaceutical S.A.E.", shortName: "MCRO", tvSymbol: "EGX:MCRO" },
  { symbol: "MEGM", name: "Middle East Glass Manufacturing SAE", shortName: "MEGM", tvSymbol: "EGX:MEGM" },
  { symbol: "MENA", name: "Mena Touristic & Real Estate Investment", shortName: "MENA", tvSymbol: "EGX:MENA" },
  { symbol: "MEPA", name: "Medical Packaging Company", shortName: "MEPA", tvSymbol: "EGX:MEPA" },
  { symbol: "MFPC", name: "Misr Fertilizers Production Company MOPCO", shortName: "MFPC", tvSymbol: "EGX:MFPC" },
  { symbol: "MFSC", name: "Misr Duty Free Shops Co.", shortName: "MFSC", tvSymbol: "EGX:MFSC" },
  { symbol: "MHOT", name: "Misr Hotels Co.", shortName: "MHOT", tvSymbol: "EGX:MHOT" },
  { symbol: "MICH", name: "Misr Chemical Industries Ltd.", shortName: "MICH", tvSymbol: "EGX:MICH" },
  { symbol: "MILS", name: "North Cairo Mills Co.", shortName: "MILS", tvSymbol: "EGX:MILS" },
  { symbol: "MIPH", name: "Minapharm Pharmaceuticals", shortName: "MIPH", tvSymbol: "EGX:MIPH" },
  { symbol: "MISR", name: "MISR Intercontinental for Granite & Marble", shortName: "MISR", tvSymbol: "EGX:MISR" },
  { symbol: "MKIT", name: "Misr Kuwait Investment & Trading Co.", shortName: "MKIT", tvSymbol: "EGX:MKIT" },
  { symbol: "MLIC", name: "Misr Life Insurance", shortName: "MLIC", tvSymbol: "EGX:MLIC" },
  { symbol: "MMAT", name: "Marsa Marsa Alam for Tourism Development", shortName: "MMAT", tvSymbol: "EGX:MMAT" },
  { symbol: "MOED", name: "Egyptian Modern Education Systems", shortName: "MOED", tvSymbol: "EGX:MOED" },
  { symbol: "MOIL", name: "Maridive & Oil Services SAE", shortName: "MOIL", tvSymbol: "EGX:MOIL" },
  { symbol: "MOIN", name: "Mohandes Insurance Co.", shortName: "MOIN", tvSymbol: "EGX:MOIN" },
  { symbol: "MOSC", name: "Misr Oils & Soap Co.", shortName: "MOSC", tvSymbol: "EGX:MOSC" },
  { symbol: "MPCI", name: "Memphis Pharmaceutical & Chemical Industries", shortName: "MPCI", tvSymbol: "EGX:MPCI" },
  { symbol: "MPCO", name: "Mansourah Poultry Co.", shortName: "MPCO", tvSymbol: "EGX:MPCO" },
  { symbol: "MPRC", name: "Egyptian Media Production City", shortName: "MPRC", tvSymbol: "EGX:MPRC" },
  { symbol: "MTIE", name: "MM Group for Industry & International Trade", shortName: "MTIE", tvSymbol: "EGX:MTIE" },
  { symbol: "NAHO", name: "Naeem Holding Co.", shortName: "NAHO", tvSymbol: "EGX:NAHO" },
  { symbol: "NARE", name: "Naeem Real Estate Holding Group", shortName: "NARE", tvSymbol: "EGX:NARE" },
  { symbol: "NCCW", name: "Nasr Co. for Civil Works", shortName: "NCCW", tvSymbol: "EGX:NCCW" },
  { symbol: "NDRL", name: "National Drilling Co.", shortName: "NDRL", tvSymbol: "EGX:NDRL" },
  { symbol: "NEDA", name: "Northern Upper Egypt Development & Agricultural Production", shortName: "NEDA", tvSymbol: "EGX:NEDA" },
  { symbol: "NHPS", name: "National Housing for Professional Syndicates", shortName: "NHPS", tvSymbol: "EGX:NHPS" },
  { symbol: "NINH", name: "Nozha International Hospital", shortName: "NINH", tvSymbol: "EGX:NINH" },
  { symbol: "NIPH", name: "El-Nile Co. for Pharmaceuticals & Chemical Industries", shortName: "NIPH", tvSymbol: "EGX:NIPH" },
  { symbol: "NMIN", name: "El Nasr Mining Co Egp10", shortName: "NMIN", tvSymbol: "EGX:NMIN" },
  { symbol: "OBRI", name: "El Obour Real Estate Investment", shortName: "OBRI", tvSymbol: "EGX:OBRI" },
  { symbol: "OCDI", name: "Six of October Development & Investment (SODIC)", shortName: "OCDI", tvSymbol: "EGX:OCDI" },
  { symbol: "OCPH", name: "October Pharma Co.", shortName: "OCPH", tvSymbol: "EGX:OCPH" },
  { symbol: "ODIN", name: "ODIN Investments", shortName: "ODIN", tvSymbol: "EGX:ODIN" },
  { symbol: "OFH", name: "O B Financial Holding", shortName: "OFH", tvSymbol: "EGX:OFH" },
  { symbol: "OIH", name: "Orascom Investment Holding SAE", shortName: "OIH", tvSymbol: "EGX:OIH" },
  { symbol: "OLFI", name: "Obour Land for Food Industries", shortName: "OLFI", tvSymbol: "EGX:OLFI" },
  { symbol: "ORAS", name: "Orascom Construction Plc", shortName: "ORAS", tvSymbol: "EGX:ORAS" },
  { symbol: "ORHD", name: "Orascom Development Egypt (S.A.E)", shortName: "ORHD", tvSymbol: "EGX:ORHD" },
  { symbol: "ORWE", name: "Oriental Weavers Carpet", shortName: "ORWE", tvSymbol: "EGX:ORWE" },
  { symbol: "PHAR", name: "Egyptian International Pharmaceutical Industries Co.", shortName: "PHAR", tvSymbol: "EGX:PHAR" },
  { symbol: "PHDC", name: "Palm Hills Development Co.", shortName: "PHDC", tvSymbol: "EGX:PHDC" },
  { symbol: "PHTV", name: "Pyramisa Hotels", shortName: "PHTV", tvSymbol: "EGX:PHTV" },
  { symbol: "POCO", name: "Port Said Container And Cargo Handling", shortName: "POCO", tvSymbol: "EGX:POCO" },
  { symbol: "POUL", name: "Cairo Poultry Co.", shortName: "POUL", tvSymbol: "EGX:POUL" },
  { symbol: "PRCL", name: "General Co. for Ceramic & Porcelain Products", shortName: "PRCL", tvSymbol: "EGX:PRCL" },
  { symbol: "PRDC", name: "Pioneers Properties for Urban Development", shortName: "PRDC", tvSymbol: "EGX:PRDC" },
  { symbol: "PRMH", name: "Prime Holding", shortName: "PRMH", tvSymbol: "EGX:PRMH" },
  { symbol: "QNBE", name: "Qatar National Bank", shortName: "QNBE", tvSymbol: "EGX:QNBE" },
  { symbol: "RACC", name: "Raya Contact Center", shortName: "RACC", tvSymbol: "EGX:RACC" },
  { symbol: "RAKT", name: "Rakta Paper Manufacturing", shortName: "RAKT", tvSymbol: "EGX:RAKT" },
  { symbol: "RAYA", name: "Raya Holding for Financial Investments SAE", shortName: "RAYA", tvSymbol: "EGX:RAYA" },
  { symbol: "RKAZ", name: "REKAZ Financial Holding", shortName: "RKAZ", tvSymbol: "EGX:RKAZ" },
  { symbol: "RMDA", name: "Tenth of Ramadan Pharmaceutical Industries & Diagnostic-Rameda", shortName: "RMDA", tvSymbol: "EGX:RMDA" },
  { symbol: "ROTO", name: "Rowad Tourism (Al Rowad) Co", shortName: "ROTO", tvSymbol: "EGX:ROTO" },
  { symbol: "RREI", name: "Arab Real Estate Investment Co.", shortName: "RREI", tvSymbol: "EGX:RREI" },
  { symbol: "RTVC", name: "Remco for Touristic Villages Construction", shortName: "RTVC", tvSymbol: "EGX:RTVC" },
  { symbol: "RUBX", name: "Rubex International for Plastic & Acrylic Manufacturing", shortName: "RUBX", tvSymbol: "EGX:RUBX" },
  { symbol: "SAIB", name: "Societe Arabe Internationale de Banque", shortName: "SAIB", tvSymbol: "EGX:SAIB" },
  { symbol: "SAUD", name: "Al Baraka Bank Egypt", shortName: "SAUD", tvSymbol: "EGX:SAUD" },
  { symbol: "SCEM", name: "Sinai Cement Co.", shortName: "SCEM", tvSymbol: "EGX:SCEM" },
  { symbol: "SCFM", name: "South Cairo & Giza Mills & Bakeries", shortName: "SCFM", tvSymbol: "EGX:SCFM" },
  { symbol: "SCTS", name: "Sues Canal Co. for Technology Settling", shortName: "SCTS", tvSymbol: "EGX:SCTS" },
  { symbol: "SDTI", name: "Sharm Dreams Co. for Tourism Investment", shortName: "SDTI", tvSymbol: "EGX:SDTI" },
  { symbol: "SEIG", name: "Saudi Egyptian Investment & Finance Co. SAE", shortName: "SEIG", tvSymbol: "EGX:SEIG" },
  { symbol: "SEIGA", name: "Saudi Egyptian Investment & Finance Co. SAE", shortName: "SEIGA", tvSymbol: "EGX:SEIGA" },
  { symbol: "SIEG", name: "Egyptian Company for Pipes and Cement Products -Siegwart", shortName: "SIEG", tvSymbol: "EGX:SIEG" },
  { symbol: "SIPC", name: "Sabaa International Company for Pharmaceutial and Chemical Industry", shortName: "SIPC", tvSymbol: "EGX:SIPC" },
  { symbol: "SKPC", name: "Sidi Kerir Petrochemicals", shortName: "SKPC", tvSymbol: "EGX:SKPC" },
  { symbol: "SMFR", name: "Samad Misr-EGYFERT", shortName: "SMFR", tvSymbol: "EGX:SMFR" },
  { symbol: "SNFC", name: "Sharkia National Food", shortName: "SNFC", tvSymbol: "EGX:SNFC" },
  { symbol: "SPHT", name: "El Shams Pyramids Co. for Hotels & Touristic Projects SAE", shortName: "SPHT", tvSymbol: "EGX:SPHT" },
  { symbol: "SPIN", name: "Alexandria Spinning & Weaving", shortName: "SPIN", tvSymbol: "EGX:SPIN" },
  { symbol: "SPMD", name: "Speed Medical SAE", shortName: "SPMD", tvSymbol: "EGX:SPMD" },
  { symbol: "SUGR", name: "Delta Sugar", shortName: "SUGR", tvSymbol: "EGX:SUGR" },
  { symbol: "SVCE", name: "South Valley Cement Co.", shortName: "SVCE", tvSymbol: "EGX:SVCE" },
  { symbol: "SWDY", name: "El Sewedy Electric Company", shortName: "SWDY", tvSymbol: "EGX:SWDY" },
  { symbol: "TALM", name: "Taaleem Management Services S.A.E", shortName: "TALM", tvSymbol: "EGX:TALM" },
  { symbol: "TANM", name: "Tanmiya for Real Estate Investment", shortName: "TANM", tvSymbol: "EGX:TANM" },
  { symbol: "TAQA", name: "TAQA Arabia", shortName: "TAQA", tvSymbol: "EGX:TAQA" },
  { symbol: "TMGH", name: "Talaat Moustafa Group Holding", shortName: "TMGH", tvSymbol: "EGX:TMGH" },
  { symbol: "TRTO", name: "TransOceans Tours", shortName: "TRTO", tvSymbol: "EGX:TRTO" },
  { symbol: "TWSA", name: "TAWASOA FOR FACTORING", shortName: "TWSA", tvSymbol: "EGX:TWSA" },
  { symbol: "UBEE", name: "United Bank SAE", shortName: "UBEE", tvSymbol: "EGX:UBEE" },
  { symbol: "UEFM", name: "Upper Egypt Flour Mills Co.", shortName: "UEFM", tvSymbol: "EGX:UEFM" },
  { symbol: "UEGC", name: "El-Saeed Contracting & Real Estate Investment Co. SCCD", shortName: "UEGC", tvSymbol: "EGX:UEGC" },
  { symbol: "UNIP", name: "Universal Co. for Paper & Packaging Materials-Unipack", shortName: "UNIP", tvSymbol: "EGX:UNIP" },
  { symbol: "UNIT", name: "United Housing Construction SA", shortName: "UNIT", tvSymbol: "EGX:UNIT" },
  { symbol: "UPMS", name: "Union Pharmacist Company For Medical Services And Investment", shortName: "UPMS", tvSymbol: "EGX:UPMS" },
  { symbol: "UTOP", name: "Utopia Real Estate Investment & Tourism SAE", shortName: "UTOP", tvSymbol: "EGX:UTOP" },
  { symbol: "VALU", name: "U Consumer Finance S.A.E", shortName: "VALU", tvSymbol: "EGX:VALU" },
  { symbol: "VERT", name: "Vertika for Industry & Trade", shortName: "VERT", tvSymbol: "EGX:VERT" },
  { symbol: "VLMR", name: "Valmore Holding", shortName: "VLMR", tvSymbol: "EGX:VLMR" },
  { symbol: "VLMRA", name: "Valmore Holding", shortName: "VLMRA", tvSymbol: "EGX:VLMRA" },
  { symbol: "WCDF", name: "Middle & West Delta Flour Mills Co.", shortName: "WCDF", tvSymbol: "EGX:WCDF" },
  { symbol: "WKOL", name: "Wadi Kom Ombo Land Reclamation", shortName: "WKOL", tvSymbol: "EGX:WKOL" },
  { symbol: "ZEOT", name: "Extracted Oils & Derivatives Co.", shortName: "ZEOT", tvSymbol: "EGX:ZEOT" },
  { symbol: "ZMID", name: "Zahraa Maadi Investment & Development", shortName: "ZMID", tvSymbol: "EGX:ZMID" },
];

export const INTERVAL_MAP: Record<string, string> = {
  "1h": "60",
  "4h": "240",
};
